2019-08-11 13:22:08 - sp	-	MESSAGE	[SP] Chargement du plugin 'es_emulator'...
2019-08-11 13:22:08 - sp	-	MESSAGE	[SP] Le plugin 'es_emulator' a été chargé avec succès.
2019-08-11 13:22:09 - sp	-	MESSAGE	[SP] Chargement du plugin 'gungame'...
2019-08-11 13:22:10 - sp	-	MESSAGE	[SP] Le plugin 'gungame' a été chargé avec succès.
2019-08-11 13:22:10 - sp	-	MESSAGE	[SP] Chargement du plugin 'wcs'...
2019-08-11 13:22:10 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/plugins/command.py", line 162, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "../addons/source-python/packages/source-python/plugins/manager.py", line 194, in load
    plugin._load()
  File "../addons/source-python/packages/source-python/plugins/instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "../addons/source-python/plugins/wcs/wcs.py", line 60, in <module>
    from .core.config import cfg_bonus_xp
  File "../addons/source-python/plugins/wcs/core/config/__init__.py", line 12, in <module>
    from ..constants.info import info
  File "../addons/source-python/plugins/wcs/core/constants/__init__.py", line 130, in <module>
    data = load(inputfile)
  File "../addons/source-python/Python3/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "../addons/source-python/Python3/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "../addons/source-python/Python3/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "../addons/source-python/Python3/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 2 column 17 (char 18)


2019-08-11 13:22:10 - sp	-	MESSAGE	[SP] Impossible de charger le plugin 'wcs'.
